<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>PupaLib.Data</PackageId>
        <Version>0.1.1</Version>
        <Authors>Artpupser</Authors>
        <Owners>Artpupser</Owners>
        <Company>Artpupser</Company>
        <Copyright>Copyright MIT LICENSE 2026</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Description>A recursive data format that allows for flexible storage of any data type.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>Data, Recursion, Set, Get, DataTree</PackageTags>
        <RepositoryUrl>https://github.com/Artpupser/PupaLib.Data.git</RepositoryUrl>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="/"/>
    </ItemGroup>

</Project>
